<?php

function d( $var )
{
    echo "<pre style=\"max-height: 800px; z-index: 9999; position: relative; overflow-y: scroll; white-space: pre-wrap; word-wrap: break-word; padding: 10px 15px; border: 1px solid #fff; background-color: #161616; text-align: left; line-height: 1.5; font-family: Courier; font-size: 16px; color: #fff; \">";
    print_r( $var );
    echo "</pre>";
}

function dd( $var )
{
    d( $var );
    exit;
}

function download_languages_list()
{
    return [
        ''               => 'English (United States)',
        'en_GB'          => 'English (UK)',
        'en_CA'          => 'English (Canada)',
        'en_AU'          => 'English (Australia)',
        'en_NZ'          => 'English (New Zealand)',
        'en_ZA'          => 'English (South Africa)',
        'af'             => 'Afrikaans',
        'ar'             => 'العربية',
        'ary'            => 'العربية المغربية',
        'as'             => 'অসমীয়া',
        'azb'            => 'گؤنئی آذربایجان',
        'az'             => 'Azərbaycan dili',
        'bel'            => 'Беларуская мова',
        'bg_BG'          => 'Български',
        'bn_BD'          => 'বাংলা',
        'bo'             => 'བོད་ཡིག',
        'bs_BA'          => 'Bosanski',
        'ca'             => 'Català',
        'ceb'            => 'Cebuano',
        'cs_CZ'          => 'Čeština',
        'cy'             => 'Cymraeg',
        'da_DK'          => 'Dansk',
        'de_DE'          => 'Deutsch',
        'de_CH'          => 'Deutsch (Schweiz)',
        'de_AT'          => 'Deutsch (Österreich)',
        'de_CH_informal' => 'Deutsch (Schweiz, Du)',
        'de_DE_formal'   => 'Deutsch (Sie)',
        'dzo'            => 'རྫོང་ཁ',
        'el'             => 'Ελληνικά',
        'eo'             => 'Esperanto',
        'es_ES'          => 'Español',
        'es_CO'          => 'Español de Colombia',
        'es_AR'          => 'Español de Argentina',
        'es_CL'          => 'Español de Chile',
        'es_PE'          => 'Español de Perú',
        'es_UY'          => 'Español de Uruguay',
        'es_CR'          => 'Español de Costa Rica',
        'es_GT'          => 'Español de Guatemala',
        'es_VE'          => 'Español de Venezuela',
        'es_MX'          => 'Español de México',
        'et'             => 'Eesti',
        'eu'             => 'Euskara',
        'fa_IR'          => 'فارسی',
        'fi'             => 'Suomi',
        'fr_FR'          => 'Français',
        'fr_BE'          => 'Français de Belgique',
        'fr_CA'          => 'Français du Canada',
        'fur'            => 'Friulian',
        'gd'             => 'Gàidhlig',
        'gl_ES'          => 'Galego',
        'gu'             => 'ગુજરાતી',
        'haz'            => 'هزاره گی',
        'he_IL'          => 'עִבְרִית',
        'hi_IN'          => 'हिन्दी',
        'hr'             => 'Hrvatski',
        'hsb'            => 'Hornjoserbšćina',
        'hu_HU'          => 'Magyar',
        'hy'             => 'Հայերեն',
        'id_ID'          => 'Bahasa Indonesia',
        'is_IS'          => 'Íslenska',
        'it_IT'          => 'Italiano',
        'ja'             => '日本語',
        'jv_ID'          => 'Basa Jawa',
        'ka_GE'          => 'ქართული',
        'kab'            => 'Taqbaylit',
        'kk'             => 'Қазақ тілі',
        'km'             => 'ភាសាខ្មែរ',
        'kn'             => 'ಕನ್ನಡ',
        'ko_KR'          => '한국어',
        'ckb'            => 'كوردی‎',
        'lo'             => 'ພາສາລາວ',
        'lt_LT'          => 'Lietuvių kalba',
        'lv'             => 'Latviešu valoda',
        'mk_MK'          => 'Македонски јазик',
        'ml_IN'          => 'മലയാളം',
        'mn'             => 'Монгол',
        'mr'             => 'मराठी',
        'ms_MY'          => 'Bahasa Melayu',
        'my_MM'          => 'ဗမာစာ',
        'nb_NO'          => 'Norsk bokmål',
        'ne_NP'          => 'नेपाली',
        'nl_NL'          => 'Nederlands',
        'nl_NL_formal'   => 'Nederlands (Formeel)',
        'nl_BE'          => 'Nederlands (België)',
        'nn_NO'          => 'Norsk nynorsk',
        'oci'            => 'Occitan',
        'pa_IN'          => 'ਪੰਜਾਬੀ',
        'pl_PL'          => 'Polski',
        'ps'             => 'پښتو',
        'pt_PT'          => 'Português',
        'pt_PT_ao90'     => 'Português (AO90)',
        'pt_BR'          => 'Português do Brasil',
        'pt_AO'          => 'Português de Angola',
        'rhg'            => 'Ruáinga',
        'ro_RO'          => 'Română',
        'ru_RU'          => 'Русский',
        'sah'            => 'Сахалыы',
        'snd'            => 'سنڌي',
        'si_LK'          => 'සිංහල',
        'sk_SK'          => 'Slovenčina',
        'skr'            => 'سرائیکی',
        'sl_SI'          => 'Slovenščina',
        'sq'             => 'Shqip',
        'sr_RS'          => 'Српски језик',
        'sv_SE'          => 'Svenska',
        'sw'             => 'Kiswahili',
        'szl'            => 'Ślōnskŏ gŏdka',
        'ta_IN'          => 'தமிழ்',
        'te'             => 'తెలుగు',
        'th'             => 'ไทย',
        'tl'             => 'Tagalog',
        'tr_TR'          => 'Türkçe',
        'tt_RU'          => 'Татар теле',
        'tah'            => 'Reo Tahiti',
        'ug_CN'          => 'ئۇيغۇرچە',
        'uk'             => 'Українська',
        'ur'             => 'اردو',
        'uz_UZ'          => 'O‘zbekcha',
        'vi'             => 'Tiếng Việt',
        'zh_TW'          => '繁體中文',
        'zh_CN'          => '简体中文',
        'zh_HK'          => '香港中文版   ',
    ];
}

function default_plugins_list()
{
    return [
        'akismet' => 'Akismet',
        'hello'   => 'Hello Dolly',
    ];
}

function default_posts_list()
{
    return [
        1 => 'Post: Hello World',
        2 => 'Page: Sample Page',
        3 => 'Page: Privacy Policy',
    ];
}

function timezone_list()
{
    return [
        'default'                        => 'Default',
        'Africa/Abidjan'                 => 'Abidjan',
        'Africa/Accra'                   => 'Accra',
        'Africa/Addis_Ababa'             => 'Addis Ababa',
        'Africa/Algiers'                 => 'Algiers',
        'Africa/Asmara'                  => 'Asmara',
        'Africa/Bamako'                  => 'Bamako',
        'Africa/Bangui'                  => 'Bangui',
        'Africa/Banjul'                  => 'Banjul',
        'Africa/Bissau'                  => 'Bissau',
        'Africa/Blantyre'                => 'Blantyre',
        'Africa/Brazzaville'             => 'Brazzaville',
        'Africa/Bujumbura'               => 'Bujumbura',
        'Africa/Cairo'                   => 'Cairo',
        'Africa/Casablanca'              => 'Casablanca',
        'Africa/Ceuta'                   => 'Ceuta',
        'Africa/Conakry'                 => 'Conakry',
        'Africa/Dakar'                   => 'Dakar',
        'Africa/Dar_es_Salaam'           => 'Dar es Salaam',
        'Africa/Djibouti'                => 'Djibouti',
        'Africa/Douala'                  => 'Douala',
        'Africa/El_Aaiun'                => 'El Aaiun',
        'Africa/Freetown'                => 'Freetown',
        'Africa/Gaborone'                => 'Gaborone',
        'Africa/Harare'                  => 'Harare',
        'Africa/Johannesburg'            => 'Johannesburg',
        'Africa/Juba'                    => 'Juba',
        'Africa/Kampala'                 => 'Kampala',
        'Africa/Khartoum'                => 'Khartoum',
        'Africa/Kigali'                  => 'Kigali',
        'Africa/Kinshasa'                => 'Kinshasa',
        'Africa/Lagos'                   => 'Lagos',
        'Africa/Libreville'              => 'Libreville',
        'Africa/Lome'                    => 'Lome',
        'Africa/Luanda'                  => 'Luanda',
        'Africa/Lubumbashi'              => 'Lubumbashi',
        'Africa/Lusaka'                  => 'Lusaka',
        'Africa/Malabo'                  => 'Malabo',
        'Africa/Maputo'                  => 'Maputo',
        'Africa/Maseru'                  => 'Maseru',
        'Africa/Mbabane'                 => 'Mbabane',
        'Africa/Mogadishu'               => 'Mogadishu',
        'Africa/Monrovia'                => 'Monrovia',
        'Africa/Nairobi'                 => 'Nairobi',
        'Africa/Ndjamena'                => 'Ndjamena',
        'Africa/Niamey'                  => 'Niamey',
        'Africa/Nouakchott'              => 'Nouakchott',
        'Africa/Ouagadougou'             => 'Ouagadougou',
        'Africa/Porto-Novo'              => 'Porto-Novo',
        'Africa/Sao_Tome'                => 'Sao Tome',
        'Africa/Tripoli'                 => 'Tripoli',
        'Africa/Tunis'                   => 'Tunis',
        'Africa/Windhoek'                => 'Windhoek',
        'America/Adak'                   => 'Adak',
        'America/Anchorage'              => 'Anchorage',
        'America/Anguilla'               => 'Anguilla',
        'America/Antigua'                => 'Antigua',
        'America/Araguaina'              => 'Araguaina',
        'America/Argentina/Buenos_Aires' => 'Argentina - Buenos Aires',
        'America/Argentina/Catamarca'    => 'Argentina - Catamarca',
        'America/Argentina/Cordoba'      => 'Argentina - Cordoba',
        'America/Argentina/Jujuy'        => 'Argentina - Jujuy',
        'America/Argentina/La_Rioja'     => 'Argentina - La Rioja',
        'America/Argentina/Mendoza'      => 'Argentina - Mendoza',
        'America/Argentina/Rio_Gallegos' => 'Argentina - Rio Gallegos',
        'America/Argentina/Salta'        => 'Argentina - Salta',
        'America/Argentina/San_Juan'     => 'Argentina - San Juan',
        'America/Argentina/San_Luis'     => 'Argentina - San Luis',
        'America/Argentina/Tucuman'      => 'Argentina - Tucuman',
        'America/Argentina/Ushuaia'      => 'Argentina - Ushuaia',
        'America/Aruba'                  => 'Aruba',
        'America/Asuncion'               => 'Asuncion',
        'America/Atikokan'               => 'Atikokan',
        'America/Bahia'                  => 'Bahia',
        'America/Bahia_Banderas'         => 'Bahia Banderas',
        'America/Barbados'               => 'Barbados',
        'America/Belem'                  => 'Belem',
        'America/Belize'                 => 'Belize',
        'America/Blanc-Sablon'           => 'Blanc-Sablon',
        'America/Boa_Vista'              => 'Boa Vista',
        'America/Bogota'                 => 'Bogota',
        'America/Boise'                  => 'Boise',
        'America/Cambridge_Bay'          => 'Cambridge Bay',
        'America/Campo_Grande'           => 'Campo Grande',
        'America/Cancun'                 => 'Cancun',
        'America/Caracas'                => 'Caracas',
        'America/Cayenne'                => 'Cayenne',
        'America/Cayman'                 => 'Cayman',
        'America/Chicago'                => 'Chicago',
        'America/Chihuahua'              => 'Chihuahua',
        'America/Costa_Rica'             => 'Costa Rica',
        'America/Creston'                => 'Creston',
        'America/Cuiaba'                 => 'Cuiaba',
        'America/Curacao'                => 'Curacao',
        'America/Danmarkshavn'           => 'Danmarkshavn',
        'America/Dawson'                 => 'Dawson',
        'America/Dawson_Creek'           => 'Dawson Creek',
        'America/Denver'                 => 'Denver',
        'America/Detroit'                => 'Detroit',
        'America/Dominica'               => 'Dominica',
        'America/Edmonton'               => 'Edmonton',
        'America/Eirunepe'               => 'Eirunepe',
        'America/El_Salvador'            => 'El Salvador',
        'America/Fortaleza'              => 'Fortaleza',
        'America/Fort_Nelson'            => 'Fort Nelson',
        'America/Glace_Bay'              => 'Glace Bay',
        'America/Goose_Bay'              => 'Goose Bay',
        'America/Grand_Turk'             => 'Grand Turk',
        'America/Grenada'                => 'Grenada',
        'America/Guadeloupe'             => 'Guadeloupe',
        'America/Guatemala'              => 'Guatemala',
        'America/Guayaquil'              => 'Guayaquil',
        'America/Guyana'                 => 'Guyana',
        'America/Halifax'                => 'Halifax',
        'America/Havana'                 => 'Havana',
        'America/Hermosillo'             => 'Hermosillo',
        'America/Indiana/Indianapolis'   => 'Indiana - Indianapolis',
        'America/Indiana/Knox'           => 'Indiana - Knox',
        'America/Indiana/Marengo'        => 'Indiana - Marengo',
        'America/Indiana/Petersburg'     => 'Indiana - Petersburg',
        'America/Indiana/Tell_City'      => 'Indiana - Tell City',
        'America/Indiana/Vevay'          => 'Indiana - Vevay',
        'America/Indiana/Vincennes'      => 'Indiana - Vincennes',
        'America/Indiana/Winamac'        => 'Indiana - Winamac',
        'America/Inuvik'                 => 'Inuvik',
        'America/Iqaluit'                => 'Iqaluit',
        'America/Jamaica'                => 'Jamaica',
        'America/Juneau'                 => 'Juneau',
        'America/Kentucky/Louisville'    => 'Kentucky - Louisville',
        'America/Kentucky/Monticello'    => 'Kentucky - Monticello',
        'America/Kralendijk'             => 'Kralendijk',
        'America/La_Paz'                 => 'La Paz',
        'America/Lima'                   => 'Lima',
        'America/Los_Angeles'            => 'Los Angeles',
        'America/Lower_Princes'          => 'Lower Princes',
        'America/Maceio'                 => 'Maceio',
        'America/Managua'                => 'Managua',
        'America/Manaus'                 => 'Manaus',
        'America/Marigot'                => 'Marigot',
        'America/Martinique'             => 'Martinique',
        'America/Matamoros'              => 'Matamoros',
        'America/Mazatlan'               => 'Mazatlan',
        'America/Menominee'              => 'Menominee',
        'America/Merida'                 => 'Merida',
        'America/Metlakatla'             => 'Metlakatla',
        'America/Mexico_City'            => 'Mexico City',
        'America/Miquelon'               => 'Miquelon',
        'America/Moncton'                => 'Moncton',
        'America/Monterrey'              => 'Monterrey',
        'America/Montevideo'             => 'Montevideo',
        'America/Montserrat'             => 'Montserrat',
        'America/Nassau'                 => 'Nassau',
        'America/New_York'               => 'New York',
        'America/Nipigon'                => 'Nipigon',
        'America/Nome'                   => 'Nome',
        'America/Noronha'                => 'Noronha',
        'America/North_Dakota/Beulah'    => 'North Dakota - Beulah',
        'America/North_Dakota/Center'    => 'North Dakota - Center',
        'America/North_Dakota/New_Salem' => 'North Dakota - New Salem',
        'America/Nuuk'                   => 'Nuuk',
        'America/Ojinaga'                => 'Ojinaga',
        'America/Panama'                 => 'Panama',
        'America/Pangnirtung'            => 'Pangnirtung',
        'America/Paramaribo'             => 'Paramaribo',
        'America/Phoenix'                => 'Phoenix',
        'America/Port-au-Prince'         => 'Port-au-Prince',
        'America/Port_of_Spain'          => 'Port of Spain',
        'America/Porto_Velho'            => 'Porto Velho',
        'America/Puerto_Rico'            => 'Puerto Rico',
        'America/Punta_Arenas'           => 'Punta Arenas',
        'America/Rainy_River'            => 'Rainy River',
        'America/Rankin_Inlet'           => 'Rankin Inlet',
        'America/Recife'                 => 'Recife',
        'America/Regina'                 => 'Regina',
        'America/Resolute'               => 'Resolute',
        'America/Rio_Branco'             => 'Rio Branco',
        'America/Santarem'               => 'Santarem',
        'America/Santiago'               => 'Santiago',
        'America/Santo_Domingo'          => 'Santo Domingo',
        'America/Sao_Paulo'              => 'Sao Paulo',
        'America/Scoresbysund'           => 'Scoresbysund',
        'America/Sitka'                  => 'Sitka',
        'America/St_Barthelemy'          => 'St Barthelemy',
        'America/St_Johns'               => 'St Johns',
        'America/St_Kitts'               => 'St Kitts',
        'America/St_Lucia'               => 'St Lucia',
        'America/St_Thomas'              => 'St Thomas',
        'America/St_Vincent'             => 'St Vincent',
        'America/Swift_Current'          => 'Swift Current',
        'America/Tegucigalpa'            => 'Tegucigalpa',
        'America/Thule'                  => 'Thule',
        'America/Thunder_Bay'            => 'Thunder Bay',
        'America/Tijuana'                => 'Tijuana',
        'America/Toronto'                => 'Toronto',
        'America/Tortola'                => 'Tortola',
        'America/Vancouver'              => 'Vancouver',
        'America/Whitehorse'             => 'Whitehorse',
        'America/Winnipeg'               => 'Winnipeg',
        'America/Yakutat'                => 'Yakutat',
        'America/Yellowknife'            => 'Yellowknife',
        'Antarctica/Casey'               => 'Casey',
        'Antarctica/Davis'               => 'Davis',
        'Antarctica/DumontDUrville'      => 'DumontDUrville',
        'Antarctica/Macquarie'           => 'Macquarie',
        'Antarctica/Mawson'              => 'Mawson',
        'Antarctica/McMurdo'             => 'McMurdo',
        'Antarctica/Palmer'              => 'Palmer',
        'Antarctica/Rothera'             => 'Rothera',
        'Antarctica/Syowa'               => 'Syowa',
        'Antarctica/Troll'               => 'Troll',
        'Antarctica/Vostok'              => 'Vostok',
        'Arctic/Longyearbyen'            => 'Longyearbyen',
        'Asia/Aden'                      => 'Aden',
        'Asia/Almaty'                    => 'Almaty',
        'Asia/Amman'                     => 'Amman',
        'Asia/Anadyr'                    => 'Anadyr',
        'Asia/Aqtau'                     => 'Aqtau',
        'Asia/Aqtobe'                    => 'Aqtobe',
        'Asia/Ashgabat'                  => 'Ashgabat',
        'Asia/Atyrau'                    => 'Atyrau',
        'Asia/Baghdad'                   => 'Baghdad',
        'Asia/Bahrain'                   => 'Bahrain',
        'Asia/Baku'                      => 'Baku',
        'Asia/Bangkok'                   => 'Bangkok',
        'Asia/Barnaul'                   => 'Barnaul',
        'Asia/Beirut'                    => 'Beirut',
        'Asia/Bishkek'                   => 'Bishkek',
        'Asia/Brunei'                    => 'Brunei',
        'Asia/Chita'                     => 'Chita',
        'Asia/Choibalsan'                => 'Choibalsan',
        'Asia/Colombo'                   => 'Colombo',
        'Asia/Damascus'                  => 'Damascus',
        'Asia/Dhaka'                     => 'Dhaka',
        'Asia/Dili'                      => 'Dili',
        'Asia/Dubai'                     => 'Dubai',
        'Asia/Dushanbe'                  => 'Dushanbe',
        'Asia/Famagusta'                 => 'Famagusta',
        'Asia/Gaza'                      => 'Gaza',
        'Asia/Hebron'                    => 'Hebron',
        'Asia/Ho_Chi_Minh'               => 'Ho Chi Minh',
        'Asia/Hong_Kong'                 => 'Hong Kong',
        'Asia/Hovd'                      => 'Hovd',
        'Asia/Irkutsk'                   => 'Irkutsk',
        'Asia/Jakarta'                   => 'Jakarta',
        'Asia/Jayapura'                  => 'Jayapura',
        'Asia/Jerusalem'                 => 'Jerusalem',
        'Asia/Kabul'                     => 'Kabul',
        'Asia/Kamchatka'                 => 'Kamchatka',
        'Asia/Karachi'                   => 'Karachi',
        'Asia/Kathmandu'                 => 'Kathmandu',
        'Asia/Khandyga'                  => 'Khandyga',
        'Asia/Kolkata'                   => 'Kolkata',
        'Asia/Krasnoyarsk'               => 'Krasnoyarsk',
        'Asia/Kuala_Lumpur'              => 'Kuala Lumpur',
        'Asia/Kuching'                   => 'Kuching',
        'Asia/Kuwait'                    => 'Kuwait',
        'Asia/Macau'                     => 'Macau',
        'Asia/Magadan'                   => 'Magadan',
        'Asia/Makassar'                  => 'Makassar',
        'Asia/Manila'                    => 'Manila',
        'Asia/Muscat'                    => 'Muscat',
        'Asia/Nicosia'                   => 'Nicosia',
        'Asia/Novokuznetsk'              => 'Novokuznetsk',
        'Asia/Novosibirsk'               => 'Novosibirsk',
        'Asia/Omsk'                      => 'Omsk',
        'Asia/Oral'                      => 'Oral',
        'Asia/Phnom_Penh'                => 'Phnom Penh',
        'Asia/Pontianak'                 => 'Pontianak',
        'Asia/Pyongyang'                 => 'Pyongyang',
        'Asia/Qatar'                     => 'Qatar',
        'Asia/Qostanay'                  => 'Qostanay',
        'Asia/Qyzylorda'                 => 'Qyzylorda',
        'Asia/Riyadh'                    => 'Riyadh',
        'Asia/Sakhalin'                  => 'Sakhalin',
        'Asia/Samarkand'                 => 'Samarkand',
        'Asia/Seoul'                     => 'Seoul',
        'Asia/Shanghai'                  => 'Shanghai',
        'Asia/Singapore'                 => 'Singapore',
        'Asia/Srednekolymsk'             => 'Srednekolymsk',
        'Asia/Taipei'                    => 'Taipei',
        'Asia/Tashkent'                  => 'Tashkent',
        'Asia/Tbilisi'                   => 'Tbilisi',
        'Asia/Tehran'                    => 'Tehran',
        'Asia/Thimphu'                   => 'Thimphu',
        'Asia/Tokyo'                     => 'Tokyo',
        'Asia/Tomsk'                     => 'Tomsk',
        'Asia/Ulaanbaatar'               => 'Ulaanbaatar',
        'Asia/Urumqi'                    => 'Urumqi',
        'Asia/Ust-Nera'                  => 'Ust-Nera',
        'Asia/Vientiane'                 => 'Vientiane',
        'Asia/Vladivostok'               => 'Vladivostok',
        'Asia/Yakutsk'                   => 'Yakutsk',
        'Asia/Yangon'                    => 'Yangon',
        'Asia/Yekaterinburg'             => 'Yekaterinburg',
        'Asia/Yerevan'                   => 'Yerevan',
        'Atlantic/Azores'                => 'Azores',
        'Atlantic/Bermuda'               => 'Bermuda',
        'Atlantic/Canary'                => 'Canary',
        'Atlantic/Cape_Verde'            => 'Cape Verde',
        'Atlantic/Faroe'                 => 'Faroe',
        'Atlantic/Madeira'               => 'Madeira',
        'Atlantic/Reykjavik'             => 'Reykjavik',
        'Atlantic/South_Georgia'         => 'South Georgia',
        'Atlantic/Stanley'               => 'Stanley',
        'Atlantic/St_Helena'             => 'St Helena',
        'Australia/Adelaide'             => 'Adelaide',
        'Australia/Brisbane'             => 'Brisbane',
        'Australia/Broken_Hill'          => 'Broken Hill',
        'Australia/Currie'               => 'Currie',
        'Australia/Darwin'               => 'Darwin',
        'Australia/Eucla'                => 'Eucla',
        'Australia/Hobart'               => 'Hobart',
        'Australia/Lindeman'             => 'Lindeman',
        'Australia/Lord_Howe'            => 'Lord Howe',
        'Australia/Melbourne'            => 'Melbourne',
        'Australia/Perth'                => 'Perth',
        'Australia/Sydney'               => 'Sydney',
        'Europe/Amsterdam'               => 'Amsterdam',
        'Europe/Andorra'                 => 'Andorra',
        'Europe/Astrakhan'               => 'Astrakhan',
        'Europe/Athens'                  => 'Athens',
        'Europe/Belgrade'                => 'Belgrade',
        'Europe/Berlin'                  => 'Berlin',
        'Europe/Bratislava'              => 'Bratislava',
        'Europe/Brussels'                => 'Brussels',
        'Europe/Bucharest'               => 'Bucharest',
        'Europe/Budapest'                => 'Budapest',
        'Europe/Busingen'                => 'Busingen',
        'Europe/Chisinau'                => 'Chisinau',
        'Europe/Copenhagen'              => 'Copenhagen',
        'Europe/Dublin'                  => 'Dublin',
        'Europe/Gibraltar'               => 'Gibraltar',
        'Europe/Guernsey'                => 'Guernsey',
        'Europe/Helsinki'                => 'Helsinki',
        'Europe/Isle_of_Man'             => 'Isle of Man',
        'Europe/Istanbul'                => 'Istanbul',
        'Europe/Jersey'                  => 'Jersey',
        'Europe/Kaliningrad'             => 'Kaliningrad',
        'Europe/Kiev'                    => 'Kiev',
        'Europe/Kirov'                   => 'Kirov',
        'Europe/Lisbon'                  => 'Lisbon',
        'Europe/Ljubljana'               => 'Ljubljana',
        'Europe/London'                  => 'London',
        'Europe/Luxembourg'              => 'Luxembourg',
        'Europe/Madrid'                  => 'Madrid',
        'Europe/Malta'                   => 'Malta',
        'Europe/Mariehamn'               => 'Mariehamn',
        'Europe/Minsk'                   => 'Minsk',
        'Europe/Monaco'                  => 'Monaco',
        'Europe/Moscow'                  => 'Moscow',
        'Europe/Oslo'                    => 'Oslo',
        'Europe/Paris'                   => 'Paris',
        'Europe/Podgorica'               => 'Podgorica',
        'Europe/Prague'                  => 'Prague',
        'Europe/Riga'                    => 'Riga',
        'Europe/Rome'                    => 'Rome',
        'Europe/Samara'                  => 'Samara',
        'Europe/San_Marino'              => 'San Marino',
        'Europe/Sarajevo'                => 'Sarajevo',
        'Europe/Saratov'                 => 'Saratov',
        'Europe/Simferopol'              => 'Simferopol',
        'Europe/Skopje'                  => 'Skopje',
        'Europe/Sofia'                   => 'Sofia',
        'Europe/Stockholm'               => 'Stockholm',
        'Europe/Tallinn'                 => 'Tallinn',
        'Europe/Tirane'                  => 'Tirane',
        'Europe/Ulyanovsk'               => 'Ulyanovsk',
        'Europe/Uzhgorod'                => 'Uzhgorod',
        'Europe/Vaduz'                   => 'Vaduz',
        'Europe/Vatican'                 => 'Vatican',
        'Europe/Vienna'                  => 'Vienna',
        'Europe/Vilnius'                 => 'Vilnius',
        'Europe/Volgograd'               => 'Volgograd',
        'Europe/Warsaw'                  => 'Warsaw',
        'Europe/Zagreb'                  => 'Zagreb',
        'Europe/Zaporozhye'              => 'Zaporozhye',
        'Europe/Zurich'                  => 'Zurich',
        'Indian/Antananarivo'            => 'Antananarivo',
        'Indian/Chagos'                  => 'Chagos',
        'Indian/Christmas'               => 'Christmas',
        'Indian/Cocos'                   => 'Cocos',
        'Indian/Comoro'                  => 'Comoro',
        'Indian/Kerguelen'               => 'Kerguelen',
        'Indian/Mahe'                    => 'Mahe',
        'Indian/Maldives'                => 'Maldives',
        'Indian/Mauritius'               => 'Mauritius',
        'Indian/Mayotte'                 => 'Mayotte',
        'Indian/Reunion'                 => 'Reunion',
        'Pacific/Apia'                   => 'Apia',
        'Pacific/Auckland'               => 'Auckland',
        'Pacific/Bougainville'           => 'Bougainville',
        'Pacific/Chatham'                => 'Chatham',
        'Pacific/Chuuk'                  => 'Chuuk',
        'Pacific/Easter'                 => 'Easter',
        'Pacific/Efate'                  => 'Efate',
        'Pacific/Enderbury'              => 'Enderbury',
        'Pacific/Fakaofo'                => 'Fakaofo',
        'Pacific/Fiji'                   => 'Fiji',
        'Pacific/Funafuti'               => 'Funafuti',
        'Pacific/Galapagos'              => 'Galapagos',
        'Pacific/Gambier'                => 'Gambier',
        'Pacific/Guadalcanal'            => 'Guadalcanal',
        'Pacific/Guam'                   => 'Guam',
        'Pacific/Honolulu'               => 'Honolulu',
        'Pacific/Kiritimati'             => 'Kiritimati',
        'Pacific/Kosrae'                 => 'Kosrae',
        'Pacific/Kwajalein'              => 'Kwajalein',
        'Pacific/Majuro'                 => 'Majuro',
        'Pacific/Marquesas'              => 'Marquesas',
        'Pacific/Midway'                 => 'Midway',
        'Pacific/Nauru'                  => 'Nauru',
        'Pacific/Niue'                   => 'Niue',
        'Pacific/Norfolk'                => 'Norfolk',
        'Pacific/Noumea'                 => 'Noumea',
        'Pacific/Pago_Pago'              => 'Pago Pago',
        'Pacific/Palau'                  => 'Palau',
        'Pacific/Pitcairn'               => 'Pitcairn',
        'Pacific/Pohnpei'                => 'Pohnpei',
        'Pacific/Port_Moresby'           => 'Port Moresby',
        'Pacific/Rarotonga'              => 'Rarotonga',
        'Pacific/Saipan'                 => 'Saipan',
        'Pacific/Tahiti'                 => 'Tahiti',
        'Pacific/Tarawa'                 => 'Tarawa',
        'Pacific/Tongatapu'              => 'Tongatapu',
        'Pacific/Wake'                   => 'Wake',
        'Pacific/Wallis'                 => 'Wallis',
        'UTC'                            => 'UTC',
        'UTC-12'                         => 'UTC-12',
        'UTC-11.5'                       => 'UTC-11:30',
        'UTC-11'                         => 'UTC-11',
        'UTC-10.5'                       => 'UTC-10:30',
        'UTC-10'                         => 'UTC-10',
        'UTC-9.5'                        => 'UTC-9:30',
        'UTC-9'                          => 'UTC-9',
        'UTC-8.5'                        => 'UTC-8:30',
        'UTC-8'                          => 'UTC-8',
        'UTC-7.5'                        => 'UTC-7:30',
        'UTC-7'                          => 'UTC-7',
        'UTC-6.5'                        => 'UTC-6:30',
        'UTC-6'                          => 'UTC-6',
        'UTC-5.5'                        => 'UTC-5:30',
        'UTC-5'                          => 'UTC-5',
        'UTC-4.5'                        => 'UTC-4:30',
        'UTC-4'                          => 'UTC-4',
        'UTC-3.5'                        => 'UTC-3:30',
        'UTC-3'                          => 'UTC-3',
        'UTC-2.5'                        => 'UTC-2:30',
        'UTC-2'                          => 'UTC-2',
        'UTC-1.5'                        => 'UTC-1:30',
        'UTC-1'                          => 'UTC-1',
        'UTC-0.5'                        => 'UTC-0:30',
        'UTC+0'                          => 'UTC+0',
        'UTC+0.5'                        => 'UTC+0:30',
        'UTC+1'                          => 'UTC+1',
        'UTC+1.5'                        => 'UTC+1:30',
        'UTC+2'                          => 'UTC+2',
        'UTC+2.5'                        => 'UTC+2:30',
        'UTC+3'                          => 'UTC+3',
        'UTC+3.5'                        => 'UTC+3:30',
        'UTC+4'                          => 'UTC+4',
        'UTC+4.5'                        => 'UTC+4:30',
        'UTC+5'                          => 'UTC+5',
        'UTC+5.5'                        => 'UTC+5:30',
        'UTC+5.75'                       => 'UTC+5:45',
        'UTC+6'                          => 'UTC+6',
        'UTC+6.5'                        => 'UTC+6:30',
        'UTC+7'                          => 'UTC+7',
        'UTC+7.5'                        => 'UTC+7:30',
        'UTC+8'                          => 'UTC+8',
        'UTC+8.5'                        => 'UTC+8:30',
        'UTC+8.75'                       => 'UTC+8:45',
        'UTC+9'                          => 'UTC+9',
        'UTC+9.5'                        => 'UTC+9:30',
        'UTC+10'                         => 'UTC+10',
        'UTC+10.5'                       => 'UTC+10:30',
        'UTC+11'                         => 'UTC+11',
        'UTC+11.5'                       => 'UTC+11:30',
        'UTC+12'                         => 'UTC+12',
        'UTC+12.75'                      => 'UTC+12:45',
        'UTC+13'                         => 'UTC+13',
        'UTC+13.75'                      => 'UTC+13:45',
        'UTC+14'                         => 'UTC+14',
    ];
}

function date_format_list()
{
    return [
        'default' => 'Default',
        'F j, Y'  => 'May 12, 2021',
        'Y-m-d'   => '2021-05-12',
        'm/d/Y'   => '05/12/2021',
        'd/m/Y'   => '12/05/2021',
    ];
}

function time_format_list()
{
    return [
        'default' => 'Default',
        'g:i a'   => '5:14 pm',
        'g:i A'   => '5:14 PM',
        'H:i'     => '17:14',
    ];
}

function weekdays_list()
{
    return [
        0 => 'Sunday',
        1 => 'Monday',
        2 => 'Tuesday',
        3 => 'Wednesday',
        4 => 'Thursday',
        5 => 'Friday',
        6 => 'Saturday',
    ];
}

function permalink_structure_list()
{
    return [
        'Default'                  => 'default',
        '/?p=123'                  => '',
        '/2021/05/12/sample-post/' => '/%year%/%monthnum%/%day%/%postname%/',
        '/2021/05/sample-post/'    => '/%year%/%monthnum%/%postname%/',
        '/archives/123'            => '/archives/%post_id%',
        '/sample-post/'            => '/%postname%/',
        '/blog/sample-post/'       => '/blog/%postname%/',
        '/news/sample-post/'       => '/news/%postname%/',
    ];
}

function fe_id()
{
    global $iteration, $number;

    $iteration = $iteration ?? 0;
    $number    = $number ?? 0;

    $iteration++;

    if ( $iteration % 2 )
        $number++;

    return 'fe-'.$number;
}

